<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('JP Service')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.min.css', 'none', false, ['onload' => 'if(media!="all")media="all"'])
                        ->prependStylesheet($this->basePath() . '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript(); ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer id="footer" class="text-center">
                <p>&copy; <?php echo date('Y') ?> by <a href="http://versover.com" target="_blank">Versover</a> <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php
        $script =  $this->inlineScript();
        $script
            ->appendFile($this->basePath() . '//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js')
            ->appendFile($this->basePath() . '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', ['conditional' => 'lt IE 9',])
            ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', ['conditional' => 'lt IE 9',])
//            ->appendFile($this->basePath() . '/js/TweenMax.min.js')
            ->appendFile($this->basePath() . '/js/script.min.js');

        echo $script;
        ?>
    </body>
</html>
